# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'SberInnovation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Pulsator'
  pod 'GoogleMaps', '6.0.1'
  pod 'FittedSheets'
  # Pods for SberInnovation

end
